### ISSUE TITLE
Rights management can be a usefull feature for this lib

### ISSUE THREAD

**Issue by JulienBourgain** [serhiisol/ng4-auth#2]
In the auth service, if you pass the route or an object with some informations from the guard, we should be able to implements some rights management.

If you add this hability to your lib, you can be able to be a great angular library ! ;)

So I will implement this feature on my side, a if I have something with a great quality like the rest of your code, i will send you a PR

**Comment by serhiisol** [comment]
Hi @JulienBourgain,

Yes that would be awesome addition, thanks ;)

**Comment by serhiisol** [comment]
Hi @JulienBourgain here's the example just in case of the library https://github.com/serhiisol/ng4-http-auth , I'll add more description in README of the repo tomorrow.

**Comment by serhiisol** [comment]
Closing issue, example provided above works perfectly with --prod. Leave a comment if you have troubles with it still
