### ISSUE TITLE
How to sign-in?

### ISSUE THREAD

**Issue by biapar** [serhiisol/ng4-auth#3]
How to sign-in?
is there an example?

**Comment by serhiisol** [comment]
Hi @biapar , I'll add full example shortly

**Comment by serhiisol** [comment]
@biapar  here's the example https://github.com/serhiisol/ng4-http-auth , I'll add more description in README of the repo tomorrow.

**Comment by serhiisol** [comment]
Closing issue, example provided above works perfectly with --prod. Leave a comment if you have troubles with it still
