### ISSUE TITLE
Error While Compiling --prod

### ISSUE THREAD

**Issue by susonwaiba** [serhiisol/ng4-auth#4]
![untitled](https://user-images.githubusercontent.com/20234104/27276390-d3b8e26c-54fa-11e7-8f1f-b38f40a81657.png)
`import { Injectable } from '@angular/core';
import { Http, Response } from '@angular/http';
import { Router } from '@angular/router';
import { LaravelService } from './laravel.service';
import { AuthService } from 'ng4-auth';
import { Observable } from 'rxjs/Observable';

@Injectable()
export class AuthenticationService {

  laravelResponse: any;

  constructor(
    private http: Http,
    private router: Router,
    private laravel: LaravelService
  ) { }

  login(accessToken: string, refreshToken: string) {
    localStorage.setItem('accessToken', accessToken);
    localStorage.setItem('refreshToken', refreshToken);

  }

  isAuthorized(): Observable<boolean> {
    const isAuthorized: boolean = !!localStorage.getItem('accessToken');
    return Observable.of(isAuthorized);
  }

  logout(): void {
    localStorage.removeItem('accessToken');
    localStorage.removeItem('refreshToken');
    location.reload(true);
  }

  getAccessToken(): Observable<string> {
    const accessToken: string = localStorage.getItem('accessToken');
    return Observable.of(accessToken);
  }

  refreshToken(): Observable<any> {
    const refreshToken: string = localStorage.getItem('refreshToken');
    return this.laravel.do_token_refresh(refreshToken);
  }

  refreshShouldHappen(response: Response): boolean {
    return response.status === 401;
  }

  isRefreshTokenRequest(url: string): boolean {
    return url.endsWith('refresh-token');
  }

}
`
Using angular 4 created using cli. can anyone solve it.? in serve mode, everything looks fine and works normally. but while using ng build --prod , above mentioned error appears on console.

**Comment by serhiisol** [comment]
@susonwaiba I'll take a look tonight

**Comment by serhiisol** [comment]
@susonwaiba I've taken a look into production and aot build and library works as expected. Here's the example - https://github.com/serhiisol/ng4-http-auth .

P.S.:
I have used angular-cli:
```
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.1.3
node: 7.10.0
os: darwin x64
@angular/animations: 4.2.4
@angular/common: 4.2.4
@angular/compiler: 4.2.4
@angular/core: 4.2.4
@angular/forms: 4.2.4
@angular/http: 4.2.4
@angular/platform-browser: 4.2.4
@angular/platform-browser-dynamic: 4.2.4
@angular/router: 4.2.4
@angular/cli: 1.1.3
@angular/compiler-cli: 4.2.4
@angular/language-service: 4.2.4
```

**Comment by serhiisol** [comment]
Closing issue, example provided above works perfectly with --prod. Leave a comment if you have troubles with it still
