### ISSUE TITLE
Naming convention ?

### ISSUE THREAD

**Issue by davidbonachera** [serhiisol/ng4-auth#5]
Since all packages use the ngx convention (ngx-datatable, ngx-bootstrap, ngx-restangular ...),

Maybe you should change it to ngx-auth ?

**Comment by serhiisol** [comment]
Hi @davidbonachera, yes you're absolutely right. I'm working on the new version already, ngx-auth. It will use angular's new HttpClient and interceptors functionality, instead of custom one. Here's the link of the branch: https://github.com/serhiisol/ng4-auth/tree/ngx-auth-2.0.0

**Comment by davidbonachera** [comment]
Didn't see the branch. Awesome i'll look into it, nice work though !

**Comment by serhiisol** [comment]
@davidbonachera ok, ngx-auth is ready to use with angular 4.3.0+
